# name: catch
# --
catch ($1Exception e) {
  $0
}
